export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const UPDATE_PARSER = 'UPDATE_PARSER'
export const CREATE_PARSER = 'CREATE_PARSER'
export const DELETE_PARSER = 'DELETE_PARSER'

export const UPDATE_COLUMN_INFO = 'UPDATE_COLUMN_INFO'
export const CREATE_COLUMN_INFO = 'CREATE_COLUMN_INFO'
export const DELETE_COLUMN_INFO = 'DELETE_COLUMN_INFO'

export const DELETE_COLUMN_GLOBAL = 'DELETE_COLUMN_GLOBAL'

