export const SET_ACTIVE_PARSER = 'SET_ACTIVE_PARSER'
export const UPDATE_COLUMN_DATA = 'UPDATE_COLUMN_DATA'
export const CREATE_COLUMN = 'CREATE_COLUMN'
export const DELETE_COLUMN_LOCAL = 'DELETE_COLUMN_LOCAL'